version: '3'

services:    
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports: 
      - "3306:3306"
    networks: 
      - gmauricio-network
    command: 
      --lower_case_table_names=0     
    environment:
        MYSQL_ROOT_PASSWORD: 123456
        MYSQL_DATABASE: cadastrodb
        MYSQL_USER: cadastro
        MYSQL_PASSWORD: cadastro123 

  api:
    build: 
      dockerfile: docker/api.dockerfile
      context: .
    image: gmauriciobr/api
    ports: 
      - 8080:8080
    networks: 
      - gmauricio-network
    environment:
      HOST_DATABASE: mysql 
    depends_on:
      - mysql   
    restart: on-failure:10     

networks: 
  gmauricio-network:
    driver: bridge